"""
Groq service for communicating with the Groq API.

This module is responsible for:
- Initializing the Groq client
- Sending conversation history to the Groq API
- Streaming AI responses

API communication is kept separate from the Streamlit UI
to maintain separation of concerns and improve reusability.
"""

from groq import Groq

from config import GROQ_API_KEY


class GroqService:
    """Handle communication with the Groq API."""

    def __init__(self):
        """Initialize the Groq API client."""

        self.client = Groq(
            api_key=GROQ_API_KEY
        )

    def stream_response(
        self,
        messages,
        system_prompt,
        model,
        temperature
    ):
        """
        Generate and stream an AI response from Groq.

        Args:
            messages (list):
                Conversation history containing user and
                assistant messages.

            system_prompt (str):
                Instructions that define the AI's behavior.

            model (str):
                Groq model used for response generation.

            temperature (float):
                Controls the variability of the generated response.

        Yields:
            str:
                Individual text chunks generated by the Groq API.
        """

        # =================================================
        # BUILD API MESSAGE HISTORY
        # =================================================

        api_messages = [
            {
                "role": "system",
                "content": system_prompt
            },
            *messages
        ]

        # =================================================
        # CREATE STREAMING API REQUEST
        # =================================================

        response = self.client.chat.completions.create(
            model=model,
            messages=api_messages,
            temperature=temperature,
            stream=True
        )

        # =================================================
        # STREAM RESPONSE CHUNKS
        # =================================================

        for chunk in response:

            content = chunk.choices[0].delta.content

            if content:
                yield content